from typing import Protocol, runtime_checkable


@runtime_checkable
class ObjectStore(Protocol):
    """Provider-neutral contract for encrypted object and catalog storage."""

    def put_bytes(self, key: str, body: bytes): ...
    def put_file(self, key, path): ...
    def get_bytes(self, key: str, expected_digest=None, expected_size=None) -> bytes: ...
    def download_file(self, key, destination, expected_digest, expected_size) -> None: ...
    def read_catalog(self): ...
    def conditional_catalog_put(self, body: bytes, expected_etag): ...
    def delete_object(self, key: str) -> None: ...
